# Chemistry

## Solution

A solution is a homogeneous mixture composed of a solute, which is the substance dissolved, and solvent, which is the substance that dissolves.\
The mixtures can be separated in different ways:

-   **Filtration**: is a method used to separate solid components from liquid or gaseous substances.
-   **Centrifuge**: is a method used to separate solid substances from the liquids, exploiting the centrifuge force. In this way, the solid particles settle on the bottom whereas the liquid substance remains in the upper portion; this liquid phase is called supernatant.
-   **Decantation**: is a process for separating mixtures by removing a precipitate-free liquid layer or settled solids from a solution, based on gravity. The aim may be to obtain a decanted liquid (particulate-free liquid) or to recover the precipitate.\

For the preparation of a solution, some aspects have to be considered. For example, solute solubility has to be known because some problems can occur for the saturation of solution. Moreover, it should be careful that the solute is well dissolved in the solvent. When the solution is clear, it has to be filtered to avoid any kind of microbial contamination: in most cases, the solution is sterilised through filtration using filters 0.22 µm: sometimes, autoclave is used to sterilise a solution depending on the kind of solute present into. Another question is correlated to the use of plastic cylinder or glass ones, depending on the temperature used for dissolving (room temperature or high temperature) or on the requirement for the metal-free solution.\

## Solubility

The solubility indicates the quantity of a solute dissolved in a solvent.\
The solubility may be expressed by using different unite of measures indicating the concentration of a solution:

-   **ppm** is the acronym of "parts per millions", and it can be also expressed in milligrams per Liter (mg/L); it corresponds to 1 µg/mL. This unit of measure indicates how many milligrams of a solute are present in 1 liter of solution.
-   **ppt** is the acronym of "parts per thousands" - and it can be also expressed in milligrams per 100 mL (mg/100 mL); it corresponds to 1 µg/mL. This unit of measure indicates how many milligrams of a solute are present in 100 milliliters of solution.
-   **ppb** is the acronym of "parts per billions" - and it can be also expressed in micrograms per Liter (ug/L). This unit of measure indicates how many micrograms of a solute are present in 1 liter of solution.
-   **Concentration (w/w)**: corresponds to weight of a solute in 100 mg of solution\
-   **Concentration (V/V)**: corresponds to volume of a solute in 100 mL of solution\
-   **Concentration (w/V)**: corresponds to weight of a solute in 100 mL of solution\
-   **Molarity (M = mol/L)**: corresponds to number of moles of solute in 1 L of solution.

The solubility of most solid substances is affected by the temperature: if the temperature increases, the solubility increases.\
The solubility of gas has a different behaviour: if the temperature increases, the solubility decreases. 

## Temperature

Temperature is a physical quantity that is a measure of hotness or coldness of matter or radiation.\
Temperature is measured with a thermometer. The most common scales are the Celsius scale (with the unit $°C$), the Fahrenheit scale (with the unit °F), and the Kelvin scale (with the unit $K$).

Conversion between the temperature scales (add TABLE)

## pH and pOH - pondus Hydrogenium and pondus OH

In chemistry, pH is a scale used to specify the acidity or basicity of an aqueous solution.\
The pH scale is logarithmic and inversely indicates the concentration of hydrogen ions in the solution.
<p align="center"> $pH = -log_{10}[H^{+}]$ </p>
The pOH scale is logarithmic and inversely indicates the concentration of hydroxide ions in the solution.
<p align="center"> $pOH = -log_{10}[OH^{-}]$ </p>
At 25°C (77°F), solutions with a pH less than 7 are acidic, while solutions with a pH higher than 7 are basic. Solutions with a pH of 7 at this temperature are neutral (for example pure water, in which there is the same concentration of $H^{+}$ ions as $OH^{-}$ ions).\

To calculate the concentration of $H^{+}$ or $OH^{-}$ in a sample with a specific pH/pOH value:\
<p align="center"> $[H^{+}]$ = $10^{-pH}$ </p>\
<p align="center"> $[OH^{-}]$ = $10^{-pOH}$ </p>\

The pH is inversely proportional to the temperature of the solution. When the temperature of a solution increases, molecular vibrations in the solution increase causing ionization and the formation of $H^{+}$ ions. More $H^{+}$ ions lead to more acidic behaviour. Due to temperature changes, the pH value of the solution changes. Therefore, pH decreases as temperature increases.\
The pH is measured with a pHmeter. If the pHmeter has the temperature probe, the pH value is calculated considering the probable changes due to temperature. If the pHmeter has not the temperature probe, the real pH value should be calculated with a pH temperature correction calculator.\
The pH value is an important variable, since it can control biological or chemical processes, the availability of nutrients or even the activity of microorganisms.

## MVpH - MilliVolt pH

The pH probe is generally a glass electrode that measures the difference in electrical potential on two sides of a thin glass membrane placed at the end of the electrode; this potential difference is linked to the difference between the concentrations of hydrogen ions at the inside and outside the membrane.\
A standard pH sensor outputs a millivolt (mV) signal, which corresponds to a pH value. Moving one pH unit along the scale in any direction will correspond to a change in voltage of 59 mV.\
-   An output of **0 mV** is equal to $pH = 7$\
-   An output, included **between 0 and -414.12 mV** (7 x -59 mV), indicates $pH > 7$\
-   An output, included **between 0 and +414.12 mV** (7 x 59 mV), indicates $pH < 7$\

## ORP - Oxidation Reduction Potential

ORP is a numerical index of the intensity of oxidizing or reducing conditions within a system. Positive values for ORP indicate oxidizing conditions, whereas negative values indicate reducing conditions.\
ORP can also be viewed as a representation of electron availability. Since reducing agents donate electrons, a reducing environment is one in which electrons are relatively available. In contrast, an oxidizing environment is one in which electrons are relatively unavailable.\
Oxidation and reduction are related chemical processes that refer to the exchange of electrons in a reaction.\

-   **Oxidation** refers to when a chemical substance loses electrons.
-   **Reduction** refers to when a chemical substance gains electrons, so reduction is the opposite of oxidation.\

Both oxidation and reduction can occur in the same reaction, which is why reactions involving oxidation and reduction are often called redox reactions.\
Chemicals (such as oxygen) that accept electrons from other compounds are called oxidizing agents, while substances (such as methane or hydrogen) that donate electrons are called reducing agents.\
Redox is expressed as electrical potential (voltage). Generally, a reducing environment is indicated by a negative reading, while an oxidizing environment is indicated by a positive reading. The most common unit for expressing redox potential is the millivolt (mV).\

## DO - Dissolved Oxygen

Dissolved oxygen is the quantity of oxygen gas ($O_{2}$), dissolved in water.\ 
In general, natural chemical processes dissolve gases such as oxygen, nitrogen and carbon dioxide in the water until saturation is reached. The amount of oxygen that can be absorbed depends on many factors, such as temperature, salinity and pressure. The greatest consumption of oxygen in water occurs through the respiration of animals, microbes and plants, but also through the decomposition of dead organic matter by microbes and fungi.\
Additionally, dissolved oxygen can decrease when the water body warms. In fact, for the preparation of anaerobic medium, the solutions are placed on a hot plate in order to cause the oxygen leakage, and to create an anaerobic environment. 
Dissolved oxygen is usually reported in milligrams per Liter ($mg/L$), in parts per million ($ppm$) or micromoles ($μmol$). The oxygen concentration is also expressed as a percentage of saturation, which is the amount of oxygen present compared to the maximum value (100%) which could be contained in a specific air volume.\

## Conductibility (spc)

Electrical conductivity, also called EC value (EC means “electrical conductivity”), is a measure of its ability to conduct electricity. The SI unit of conductivity is Siemens per meter ($S/m$).\
This parameter depends on the substances dissolved in a solution.\
Conductivity measurements are routinely used in many industrial and environmental applications as a quick, economical, and reliable method of measuring the ionic content in a solution.\
In many cases, conductivity is directly linked to total dissolved solids (TDS).\

## TDS - Total Dissolved Solids

Total dissolved solids (TDS) is a measure of the combined dissolved content of all inorganic and organic substances present in water. Total dissolved solids (TDS) include inorganic salts, primarily calcium, magnesium, potassium, sodium, bicarbonates, chlorides and sulfates, and some small amounts of organic matter that are dissolved in water.\
TDS concentrations are usually in parts per million ($ppm$).

## Salinity

The salinity describes the amount of dissolved salts in a liquid.\
In most cases, sodium chloride ($NaCl$) represents the largest percentage of dissolved salts.\
Typical units for salt content are $g/kg$ (g salt per kg of solution), $%$, $ppt$ or even $PSU$.\
There is a proportionality between the salinity and conductivity. If a salt content increases, the conductivity value increases. For this reason, the salinity values can be calculated, if the conductivity value is known.

## Density

The density of a substance is the ratio between the mass of the substance and volume (how much space it takes up). Its unit of measure in the International System is $kg/m3$.

## Alkalinity

Alkalinity is a measure of water's ability to resist pH changes that lead to acidity, or to neutralize acids and maintain a stable pH. This capacity is usually referred to as the "buffer capacity" of water.\
The presence of some chemical substances, including hydroxides, carbonates and bicarbonates, affects the alkalinity of water. In simple terms, water with high alkalinity is less likely to become more acidic if it is contaminated with acidic water, such as acid rain.\
Alkalinity is measured by a process called titration. An acid of known concentration, called a titrant, is added to the water.The amount of acid used to bring the water up to a specific pH level is determined by the alkalinity of the water. Once the water reaches the pH end point, it changes colour.\
Alkalinity is measured in units of milligrams per liter (mg/L) of calcium carbonate $(CaCO_{3})$. Alkaline water has a pH of 8 or higher. The pH scale is used to measure the alkalinity of water.Water with a pH between 8 and 10 is considered slightly alkaline, while water with a pH above 10 is considered very alkaline. A pH of 7 is neutral, while anything below 7 is considered acidic.

## Melting Temperature

It can refer to:\

-   **Melting point**: is the temperature at which a substance changes from a solid to a liquid state 
-   **Melting temperature**: is the temperature at which the DNA double helix dissociates into single strands.

## Gas laws

$Henry’s law$ \
The solubility of a gas in a liquid sample is directly proportional to pressure gas on the liquid phase.\
Example: in a carbonated drink, the carbon dioxide (gas) is present and it exercises a pressure in the bottle, higher than atmospheric pressure, which allows it to be soluble in the liquid phase. When the bottle is opened, the carbon dioxide pressure decreases with the consequent decreasing of its solubility. The observed result is the leakage of many bubbles from the liquid phase.

$Boyle’s law$\
At constant temperature, a gas volume is inversely proportional to subjected pressure\
<p align="center"> $P x V = k$ </p>

$Charles’ law$\
At constant pressure, a gas volume is directly proportional to its temperature\
<p align="center"> $\frac{V}{T} = k$ </p>

