# Extreme Environments

## Sea ice, permafrost and polar regions
The polar regions are the areas located between the North or South Pole and the Arctic or Antarctic Circles marked by dashed lines at 66°33′ north or south latitude on the world maps, respectively.\
The extremely cold climate in both Arctic and Antarctic regions is basically related to the following factors:

-   There is an undersupply of **solar energy** throughout both the Arctic and the Antarctic, compared to other parts of the world, because of the low angle of arriving sunlight, the slope of the Earth's axis, and the orbit of this planet around the sun.\
-   The **wind circulation** around the world, caused by the differential heating between the poles and the equator as well as the rotation of Earth (Coriolis effect), acts as shields for preventing tropical heat from reaching the Arctic and Antarctic.\
-   Due to the **high albedo** of white snow and ice covers, the Earth's surface in both Arctic and Antarctic reflects a large proportion of incoming solar radiation, and thus, amplifies cooling conditions in a positive feedback.\
-   **Humidity**, the capacity of air to hold water vapor, is basically very low due to the extremely cold climate conditions.\

Soils across the polar regions harbor diverse microorganisms, which dominate the biogeochemical cycling. However, polar soil microbial diversity is largely underrepresented, and has not been directly compared with the non-polar regions at a global scale, which hinders our understanding of the potential importance of polar microbial diversity.\
Soil microorganisms are fundamental components of polar ecosystems, where plants and 58 animals are greatly limited by the harsh environments. Microorganisms are dominant drivers of biogeochemical cycles, and influence both climate change and ecosystem functions in polar regions.\
The microorganisms in the three poles are subjected to high levels of abiotic stresses, including yearly low temperatures, low water availability (in some polar soils) and extreme UV radiation fluxes, which are substantially distinct from the non-polar regions.\

## Cold seeps and mud volcanoes
Cold seeps are the areas of the ocean floor where hydrogen sulfide, methane, and other hydrocarbon-rich fluid seepage occur. Such seeps occur over fissures on the seafloor caused by tectonic activity. Fluid seepage out of those fissures gets diffused by sediment, and emerges over an area several hundred meters wide. Cold seeps constitute a biome supporting several endemic species of animals and plants. These seeps develop unique topography over time, where reactions between methane and seawater create carbonate rock formations and reefs. These reactions may also be dependent on bacterial activity.\
Finding and understanding cold seeps is important because they have global significance for the transfer of methane carbon from long-term storage in ocean-floor sediments into the ocean and atmosphere. Released methane is often oxidized to carbon dioxide, leading to changes in ocean chemistry, such as ocean acidification.\

## Shallow water-hydrothermal vents
Geothermal system are extreme environments characterized by high temperatures, a low pH, and high gas emissions, of which the greenhouse gas carbon dioxide $(CO^{2})$ is dominant. Additionally, several reduced gases are emitted in variable concentrations, including hydrogen sulfide $(H_{2}S)$, hydrogen $(H_{2})$, carbon monoxide (CO), ammonia $(NH_{3})$, and the potent greenhouse gas methane $(CH_{4})$. These gases are the driving force for the formation of a predominantly chemolithoautotrophic microbial community. Besides $(CH_{4})$, $H_{2}$ is an abundant gas in volcanic and geothermal ecosystems that can be used by members of the microbial community as an electron donor. The low $O_{2}$ concentrations within these soils facilitate microaerobic $H_{2}$ oxidation using oxygensensitive hydrogenases. Localized spots without any $O_{2}$ could give rise to anaerobic $H_{2}$ consumption, for example, by autotrophic sulfate-reducing microorganisms or hydrogenotrophic methanogens. Methanogens are often detected in volcanic/geothermal environments, especially in the deeper anaerobic layers of the soil. Geothermal ecosystems are low in organic carbon, but $CO_{2}$ is highly available and can be assimilated into biomass by chemolithoautotrophic microorganisms.

Shallow-water hydrothermal vents (<200 m in depth) have a widespread biogeographical distribution, generally associated with active submarine volcanism. In these areas, the presence of deep seated magma and deep faults, caused by tectonic activity, drives hydrothermal fluids circulation. Hydrothermal fluids are emitted from vents, which represent an opening through Earth’s crust.\
Because of their proximity to the surface, shallow-water hydrothermal systems are influenced both by geothermally generated reducing power and by light, and can be described as “high energy” environments, where microbial metabolism is fueled by different energy sources.\ 
Another potential source of heat that can drive hydrothermal circulation is exothermal geochemical (weathering) reactions (e.g., serpentinization). For each of these hydrothermal systems, resulting vent fluids are often highly enriched in reducing inorganic chemical species (electron donors) which, when mixed with oxidized seawater (with abundant electron acceptors), can generate aqueous solutions with multiple redox disequilibria readily exploited by archaeal and bacterial microbial communities.

They are characterized by a fluid temperature range of 10–119◦C. Many shallow-water hydrothermal vents show high concentrations of compounds and metal elements involved in biogeochemical cycles, including carbon, sulphur, methane, and iron. Due to these extreme conditions, shallow-water vents are outstanding environments to investigate the diversity of microorganisms involved in organic matter synthesis, breakdown or mineralization, metal cycles and interactions with fauna.\

## Hot-springs, fumaroles and mud volcanoes
Hydrothermal vents, or **hot springs**, are areas where geothermally heated water discharges through a planet's crust onto the surface, either subaerially or subaqueously. They occur in areas where there is an adequate heat source to drive fluid circulation. On Earth, this heat is primarily derived from tectonic activity near plate boundaries, either through magma generation or faulting.\

**Terrestrial mud volcanoes (MVs)** are an important natural source of methane emission.\
Mud volcanoes (MVs) are prominent surface expressions in compressional tectonic regimes. Often, methane with $CO_{2}$ and minor amounts of $C^{2+}$ hydrocarbons constitute the emitted phase. The quantity of methane emission is primarily controlled by in situ microbial production and consumption near the surface. Methane is either directly released into the atmosphere or oxidized with electron acceptors within sediments or from surface (e.g., oxygen, sulfate, or metal oxides).\
Most terrestrial MVs are characterized by a limited availability of sulfate (<1 mM). Such a low quantity of sulfate would increase the free energy (less negative) and drive sulfate-dependent anaerobic oxidation of methane (AOM) less energetically favorable.\

A **fumarole** is an opening in the crust of the Earth and is often found in areas surrounding volcanoes, which emits steam (forms when superheated water vaporizes as its pressure drops when it emerges from the ground) and gases such as carbon dioxide, sulfur dioxide, and hydrogen sulfide.\
Cracks present in actively degassing geothermal soils are of great importance since gas is often pressure-driven, contrary to non-geothermal soil where gas movements are generally only driven by concentration gradients. Gas flow is, therefore, often focused in small areas, sometimes becoming open vents, known as fumaroles, where hydrothermal gases are directly released into the atmosphere. The gases themselves interact and modify the soil, and the most effective agents are temperature and pH. Kinetic/thermal energy allows them to flow up and rules the gas-water-rock interactions. Due to these interactions, during their ascent to the surface, the volcanic/geothermal gases are depleted in some species (such as $SO_{2})$ and enriched in others (such as $CH_{4}$ and $H_{2}S$).\

## Hyperacidic lakes and volcanoes
Hyperacidic volcanic lakes are some of the most extreme geochemical environments in the present day earth’s crust. They provide a trace of the true scale of heat and mass transfer in active volcanoes and are implicated in their collapse and eruption histories.\
The escape of high-temperature gases from intrusions provides the heat and many of the raw materials for the chemistry of lakes hosted by active volcanic systems. The gas mixture released by crystallizing magmas is dominated by water (85–95 mol %) with the remainder made up of carbon dioxide $(CO_{2}$) and sulfur dioxide $(SO_{2})$, and lower concentrations of hydrogen chloride (HCl), hydrogen sulfide $(H_{2}S)$, hydrogen fluoride (HF), hydrogen $(H_{2})$, and other gases. Most of the heat transferred by this gas mixture is due to the large water component while the acidic gases ($SO_{2}$ and HCl) are primarily responsible for the distinctive chemistry of acidic lakes.\
Condensation of gas mixtures near the surface and on entry into a cool lake basin results in the formation of acidic lake water.\
Sulfur dioxide gas reacts with water to form sulfuric acid $(H_{2}SO_{4})$ and hydrogen sulfide $(H_{2}S)$ through a simple reaction such as:

$4SO_{2} + 4H_{2}O = 3H_{2}SO_{4} + H_{2}S$

The acid thus formed reacts aggressively with rocks below and around the lake and is responsible for the suspended burden of amorphous silica, sulfur, and anatase (titanium oxide, $TiO_{2})$ particles that give rise to spectacular lake coloration.\
Geological associations lead to the widely accepted explanation that acidic volcanic lakes are a ‘cold trap’ for expanding magmatic gas, that, close by, is otherwise expressed as active, high temperature fumaroles and extensive rock alteration (solfatara), and by ash and gas plumes from more active volcanoes.\
Hyperacidic volcanic lakes are expressions of much larger scale magmatic gas expansion inside volcanoes from source to surface. Their temperature and acidity are sustained by the capture of heat and $SO_{2}$ (and HCl) and a suite of metals and metalloids, including Cu, Fe, As, Au, Bi, Se, Te, and Sb, from the magmatic gas. These lakes, together with high temperature fumaroles, therefore provide clues about the physics and chemistry of high temperature gas flow at the volcano scale that otherwise are inaccessible to direct observation.\

## Deserts and arid environments 
Deserts (arid lands/drylands) constitute about 35% of the land areas of the world and are typically characterized by rainfall scarcity, higher temperatures and evapotranspiration, lower humidity, and a general paucity of vegetation cover.\
Arid environments are defined by the lack of water availability, which is directly related to the mean annual precipitation (MAP), and high values of solar irradiation, which impacts the community composition of animals, plants, and the microbial structure of the soil.\
In the soil microbiome, bacteria are the most abundant and diverse organisms, and their presence is crucial for plant growth. As arid environments display scarce vegetation, the presence and abundance of bacteria are essential for nutrient cycling and carbon storage.\

## Acid mine drainage
Acid mine drainage (AMD) or acid metalliferous drainage is the wastewater resulting from mining activities. It has been considered as a pollutant of serious concern because of its acidic nature, high content of toxic metal ions (Fe, Zn, Cd, Al, Cu, Pb), dissolved anions (sulfates, nitrates, chlorides, arsenates, etc.), hardness, and suspended solids.\
The pH of AMD ranges around 2–4. The sulfate concentration ranges from 100 to 5000 mg/L$^{−1}$. Metal-rich mine wastewater is generated due to accelerated oxidation of iron pyrite $(FeS_{2})$ and other sulfide minerals during mining activities.\
AMD exerts negative effects on the environment by: adding metals to aquatic ecosystems; altering water chemistry; decreasing the amount of oxygen available for aquatic organisms; precipitation of metals (ferric hydroxide, aluminum hydroxide etc.), leading to reduced availability of light to aquatic ecosystems; changing water quality.\
Acidic nature of AMD destroys vegetation, accelerates soil erosion, and increases the susceptibility of aquatic animals to disease. Because of these environmental concerns AMD needs to be treated before release in the environment.\

## Deep-sea anoxic lakes and brines
Deep hypersaline anoxic basins (DHABs) are unique water bodies occurring within fractures at the bottom of the sea, originated from the re-dissolution of evaporitic deposits buried under layers of sediments and exposed to seawater because of tectonic activity. This re-dissolution process generates the DHABs and a gradient of salinity, the brine-seawater interface (BSI), at the boundary between the hypersaline water mass and seawater. Such a salinity gradient is a halocline where the salt dissolution increases the water density determining a pycnocline. In parallel to the gradient of salinity and density a chemocline occurs with gradients of the many chemical species that form redox couples capable of supporting different microbial metabolisms.\
 DHABs have been described in the Gulf of Mexico, the Mediterranean Sea, the Black Sea and the Red Sea.\
Due to the high density, these brine pools hardly mix with the overlying deep seawater, and are often considered as lakes at the bottom of the sea.\

## Deep-sea hydrothermal vents
Deep-sea hydrothermal vents are regions of the sea floor at which hot, anoxic, chemical-rich water is released into the cold, oxic, deep ocean.\
Hydrothermal vents are formed when seawater percolates through cracks in the ocean crust into the subsurface. During this process, the water heats up and reacts with hot rocks, enriching it with a variety of chemicals and volatile gases. This buoyant hydrothermal fluid rises and emerges from orifices in the sea floor, rapidly mixing with cold seawater and providing a redox interface at which chemical sources of energy support vent ecosystems. In contrast to most ecosystems, which are fuelled by photosynthesis, vent communities depend on chemosynthesis. Vent microorganisms, including animal symbionts, members of microbial mats and free- living cells, use the energy produced by oxidation of sulfur, hydrogen, methane and iron to fix carbon. In turn, this organic carbon supports dense animal communities largely through symbiotic relationships with bacteria but also via grazing or suspension feeding and subsequent trophic transfer.\

Fluids emerging from vents carry reduced chemical species (for example, hydrogen sulfide, $Fe_{2+},$ hydrogen gas and methane) that are electron sources for chemolithoautotrophic growth.\

Vent fluids range from acidic to highly alkaline, not only demanding capacity for pH homeostasis but also shaping the availability of dissolved inorganic carbon (concentrations are higher at lower pH), which is required in excess for the rapid chemoautotrophic growth exhibited by bacteria–animal consortia such as the giant tubeworm Riftia pachyptila. Hot, acidic fluids often hold sufficient carbon dioxide, which is obtained directly by animals, whereas carbon dioxide may be limiting in cold, neutral or basic fluids, thus requiring mechanisms for carbon uptake and concentration. Hydrothermal fluids also contain several toxic compounds, such as heavy metals (copper, cadmium and lead) and hydrogen sulfide, that require specific adaptations.\

## Serpentinizing environments
The Earth’s subsurface is predicted to be an expansive habitat for microorganisms. Unlike surface biomes, the subsurface is largely decoupled from photosynthetic primary production; instead, many subsurface ecosystems are influenced by carbon and energy liberated from the Earth’s mantle and crust. However, given the inherent lack of accessibility, direct sampling of subsurface, rock-hosted environments has been limited.\
Serpentinization is a globally relevant subsurface process caused by the hydration of iron and magnesium rich minerals within the Earth’s crust which subsequently releases hydrogen gas. The hydrogen produced, in addition to other reduced compounds generated, can serve as the energetic basis for microbial food webs.\
Serpentinization is a widespread geochemical process associated with aqueous alteration of ultramafic rocks that produces abundant reductants $(H_{2}$ and $CH_{4})$ for life to exploit, but also potentially challenging conditions, including high pH, limited availability of terminal electron acceptors, and low concentrations of inorganic carbon. As a consequence, past studies of serpentinites have reported low cellular abundances and limited microbial diversity.\
Serpentinization is a widespread geochemical process involving the aqueous alteration of peridotite to serpentine minerals, resulting in an abundance of potential reductants, in the form of hydrogen, methane, and small organic molecules. Serpentinization also releases hydroxyl ions, which creates extremely high pH fluids (pH > 10). At high pH, bicarbonate and carbonate are the dominant species of dissolved inorganic carbon (DIC), and the latter can precipitate out of solution as carbonate minerals when in the presence of divalent cations, such as $Ca^{2+}$ and $Mg^{2+}$ commonly found in serpentinite fluids. Thus, fluids associated with serpentinization are characteristically low in DIC, particularly dissolved $CO_{2}$. Compared to the abundance of reductants in these systems, there is a lack of corresponding oxidants, which likely limits the range of potential microbial metabolisms. Thus subsurface serpentinite environments are characterised by unusual challenges to life, such as extreme pH (>10), limited availability of dissolved carbon, and a lack of potential terminal electron acceptors.\

## Deep-sea sediments and trenches
Deep-sea environments compose the largest habitat on Earth and are a major carbon sink on the planet. Even though they present harsh environmental conditions, such as low temperatures (-1 to 4°C), high hydrostatic pressure, absence of solar radiation, and low supply of organic matter, these environments harbour microbial assemblages with high genetic and metabolic diversity. A third of the total Bacteria and Archaea cells on Earth are located in the deep oceanic subsurface and 4% are in the upper 10–50 cm of oceanic sediments. Microbes play a vital role in deep-sea environments, driving a wide range of processes, including those related to biogeochemical cycles, organic matter remineralization, and primary production by chemosynthetic organisms. In these environments, most of the total microbial cell biomass appears to be composed of bacteria, although it may change towards anoxic subsurfaces, where archaea can dominate.\

## Soda lakes and hypersaline lakes 
Soda lakes and soda deserts are naturally occurring alkaline environments. They represent the most stable high-pH environments on Earth, where large amounts of carbonate minerals can generate pH values of 11.5. Although these environments are widely distributed, they are often located in inaccessible continental interiors.\
The conditions necessary for the formation of a soda lake have much in common with those for the generation of an athalassohaline salt lake, but with the major difference that in a soda lake carbonate (or carbonate complexes) becomes the major anion in solution. The most important contributing factor is a lack of alkaline earth cations $(Ca^{2+}$ and $Mg^{2+})$ in the surrounding topography, which essentially means an absence of rocks of sedimentary origin. Further circumstances include a shallow depression forming a closed drainage basin with a high marginal relief, having sufficient rainfall to sustain streams entering the basin to produce a standing body of water. In arid zones with high rates of evaporation exceeding inflow, salts accumulate by evaporative concentration.\
One of the noticeable features of many soda lakes is their colour. The water may be various shades of green or red because of the massive blooms of microorganisms. This colouring is a reflection of the very high primary productivity associated with these lakes. The almost unlimited supply of $CO_{2}$ combined with high ambient temperatures and high daily light intensities in the tropics contribute to making the East African soda lakes among the most productive of the naturally occurring aquatic environments in the world. The photosynthetic primary productivity, mainly the result of the dense populations of cyanobacteria, presumably supports the rest of the microbial community. 
In contrast to aerobic habitats, the anaerobic alkaline environment has received little attention. Because these are very productive environments with a concomitant shortage of dissolved $O_{2}$, anaerobic processes are bound to play a significant role.\

Hypersaline ecosystems are widely distributed habitats including a variety of terrestrial lakes and deep-sea basins with salt concentrations exceeding three times seawater up to saturation. In addition to being hypersaline, these ecosystems are often characterized by other extremes in environmental conditions such as high alkalinity, low oxygen concentration and high UV irradiation. Hypersaline habitats can be divided into two main types, thalassohaline- and athalassohaline waters. Thalassohaline waters or brines are of marine origin and have an ionic composition similar to that of seawater, with sodium chloride as the predominant salt and are often found in close proximity to seas and oceans. These include industrial solar salterns and natural shallow basins that became detached from the sea or ocean. Athalassohaline waters or brines such as the Dead Sea and soda lakes are often found inland and therefore not directly connected to marine waters. These brines are shaped by the dissolution of mineral salt deposits of continental origin, which are dominated by potassium-, magnesium-, sodium- and carbonate ions. Although high salinity is generally considered lethal for most organisms, hypersaline environments are often teeming with life and can harbor high biomass of functional and taxonomical diverse communities.\

## Nuclear contaminated sites
In the past decade, uranium mining, military activities and nuclear power plant accidents have introduced anthropogenic radioactive contaminants into the environment.\
Due to their intrinsic properties (i.e. radioactive decay half-life, volatility and mobility), most of these radionuclides (RNs) are highly persistent in the terrestrial environment. Radiations emitted by RNs present either in the environment or accumulated inside organisms are able to ionize atoms or molecules, with potential consequent damage to living cells. Level of such biological detriment is linked to the energy deposited into organisms exposed to ionizing radiation, under the consensual assumption of additive effects. 
Soil microorganisms and RNs display complex relationships with each other. On the one hand, bacteria can interact with RNs via multiple mechanisms including bioreduction, biomineralization, bioaccumulation or biosorption.  On the other hand, RNs may exert radio- and chemotoxic effects on bacteria, thus influencing the structure and activity of microbial communities.\