on:
  push:
     branches:
       - main

name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    #   - uses: r-lib/actions/setup-r@v2
    #     with:
    #       r-version: '4.3.0' # The R version to download (if necessary) and use. 
    # # Use "renv" to retrieve R version recorded in renv.lock file.
    #   - uses: r-lib/actions/setup-pandoc@v2
    #   - name: Install rmarkdown
    #     run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
    #   - name: Render Book
    #     run: Rscript -e 'bookdown::render_book("index.Rmd")'
    #   - uses: actions/upload-artifact@v3
    #     with:
    #       name: _book
    #       path: _book/
